# Permalinks
#
permalink:            pretty

# Setup
title:                wonderfly
tagline:              'Blog'
description:          'Technical book reading notes, Spanish notes, and more.'
url:                  http://localhost:4000/
baseurl:              ''
paginate:             5

# Custom vars
version:              1.0.0

theme: jekyll-theme-slate
