# Permalinks
#
permalink: pretty

# Setup
title: wonderfly
tagline: 'Blog'
description: 'Reading notes, personal blogs, and more.'
url: http://localhost:4000
baseurl: ''
paginate: 5
theme: jekyll-theme-slate
plugins:
    - jekyll-toc
