# Permalinks
#
permalink: pretty

# Setup
title: wonderfly
tagline: 'Blog'
description: 'Spanish study notes, technical reading notes, and more'
url: http://localhost:4000
baseurl: ''
paginate: 5
theme: jekyll-theme-slate
