# Permalinks
#
permalink:           pretty
# Use of `relative_permalinks` is deprecated:
# https://help.github.com/articles/page-build-failed-relative-permalinks-configured/
# relative_permalinks: true

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# Custom vars
version:             1.0.0
